### ISSUE TITLE
Ability to cache GET requests that include a message body

### ISSUE THREAD

**Issue by cgagon** [plataformatec/faraday-http-cache#80]
It's legal, although perhaps controversial in terms of REST, to include a message body in a GET.   For example, there are services such as Elasticsearch which require a verbose JSON-encoded message be included in the body along with the search endpoint in the URI in order to use its query DSL.  

As such, we'd like to be able to leverage this caching middleware but in order to do so, the message body needs be included in the strings that are fed to the SHA1 hexdigest when constructing the cache key.  This is of course straightforward in and of itself.  The problem arises in workflows where the cache should be invalidated and only the relevant resource URI is given.

In the current implementation, a cache prefix and the url are used to construct the key.   And when invalidating the cache the URL is fed back to the storage instance:  https://github.com/plataformatec/faraday-http-cache/blob/master/lib/faraday/http_cache.rb#L285-L290 

Has anyone attempted to solve this problem previously?  It would be helpful to support caching messages with the body included in the hexdigest for the key, but invalidation needs to be solved in order for this to be a safe general purpose modification to the middleware.

**Comment by lucasmazza** [comment]
@cgagon I think in such cases one might implement this through a generic caching like dalli or `Rails.cache` rather than in the HTTP level, since using the GET body makes it way more complicated to deal with invalidations and request equivalence inside the caching logic.

Regardless of the solution, we rather keep the gem spec compliant without adding non standard rules to how the middleware works on dealing with the cache.
